### ISSUE TITLE
Errors with included ruby 2.7.0

### ISSUE THREAD

**Issue by Fguhhla** [chef/chef-workstation#1687]
## Description
at kitchen converge we get the following error:
```
❯ kitchen converge

-----> Starting Test Kitchen (v2.10.0)
#<Thread:0x0000000002ce59d0 /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:471 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
30: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
29: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/command.rb:166:in `block (2 levels) in run_action'
28: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/command.rb:195:in `run_action_in_thread'
27: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/command.rb:195:in `public_send'
26: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:139:in `converge'
25: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:390:in `transition_to'
24: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:390:in `each'
23: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:391:in `block in transition_to'
22: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/lifecycle_hooks.rb:46:in `run_with_hooks'
21: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/lifecycle_hooks.rb:68:in `run'
20: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/lifecycle_hooks.rb:68:in `each'
19: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/lifecycle_hooks.rb:73:in `block in run'
18: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/lifecycle_hook/remote.rb:22:in `run'
17: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/transport/ssh.rb:139:in `execute'
16: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/transport/ssh.rb:382:in `execute_with_exit_code'
15: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/transport/ssh.rb:435:in `session'
14: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/transport/ssh.rb:336:in `establish_connection'
13: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/transport/ssh.rb:356:in `retry_connection'
12: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/transport/ssh.rb:337:in `block in establish_connection'
11: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh.rb:255:in `start'
10: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:72:in `authenticate'
9: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:72:in `each'
8: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:86:in `block in authenticate'
7: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
6: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:113:in `each_identity'
5: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:204:in `agent'
4: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/agent.rb:68:in `connect'
3: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/agent.rb:105:in `negotiate!'
2: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/agent.rb:221:in `send_and_wait'
1: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/agent.rb:211:in `read_packet'
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/buffer.rb:147:in `append': can't modify frozen String: "" (FrozenError)
Traceback (most recent call last):
30: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
29: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/command.rb:166:in `block (2 levels) in run_action'
28: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/command.rb:195:in `run_action_in_thread'
27: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/command.rb:195:in `public_send'
26: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:139:in `converge'
25: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:390:in `transition_to'
24: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:390:in `each'
23: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/instance.rb:391:in `block in transition_to'
22: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/lifecycle_hooks.rb:46:in `run_with_hooks'
21: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/lifecycle_hooks.rb:68:in `run'
20: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/lifecycle_hooks.rb:68:in `each'
19: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/lifecycle_hooks.rb:73:in `block in run'
18: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/lifecycle_hook/remote.rb:22:in `run'
17: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/transport/ssh.rb:139:in `execute'
16: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/transport/ssh.rb:382:in `execute_with_exit_code'
15: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/transport/ssh.rb:435:in `session'
14: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/transport/ssh.rb:336:in `establish_connection'
13: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/transport/ssh.rb:356:in `retry_connection'
12: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/transport/ssh.rb:337:in `block in establish_connection'
11: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh.rb:255:in `start'
10: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:72:in `authenticate'
9: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:72:in `each'
8: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:86:in `block in authenticate'
7: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
6: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:113:in `each_identity'
5: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:204:in `agent'
4: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/agent.rb:68:in `connect'
3: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/agent.rb:105:in `negotiate!'
2: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/agent.rb:221:in `send_and_wait'
1: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/agent.rb:211:in `read_packet'
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/buffer.rb:147:in `append': can't modify frozen String: "" (FrozenError)
```

## Chef Workstation Version
21.1.247 and  20.10.168
(with an older version 0.18.3 with ruby 2.6 it works fine)

## Platform Version
oracle linux 7

**Comment by marcparadise** [comment]
@fguhhla could you confirm this is happening on the latest version of Workstation, which ships 2.7.2?  You might also want to temporarily rename `~./chefdk` to ensure no locally installed gems are having an effect.

**Comment by tas50** [comment]
We've updated to 3.0.1 so I'm going to close this out now. If it's still a problem feel free to open a new issue
