### ISSUE TITLE
After install chef-workstation - curl not working

### ISSUE THREAD

**Issue by kmf** [chef/chef-workstation#1830]
After my installation of chef-workstation (via brew) my `curl` in my `$PATH` got overridden from 
```
/usr/bin/curl
```
to this

![2021-03-16_5-14-14](https://user-images.githubusercontent.com/78700/111255529-ec35f780-861f-11eb-8f30-fba0f59e9903.png)

using macOS 11.2.3
```
chef-workstation-21.2.303-1.x86_64.dmg
```

**Comment by johnmccrae** [comment]
I came here to post this too. I get the following output :

`¥ Johns-MBP.hsd1.or.comcast.net {/Users/johnmccrae} curl
dyld: Library not loaded: /usr/local/opt/zstd/lib/libzstd.1.dylib
  Referenced from: /opt/chef-workstation/embedded/bin/curl
  Reason: no suitable image found.  Did find:
	/usr/local/opt/zstd/lib/libzstd.1.dylib: code signature in (/usr/local/opt/zstd/lib/libzstd.1.dylib) not valid for use in process using Library Validation: mapping process and mapped file (non-platform) have different Team IDs
	/usr/local/opt/zstd/lib/libzstd.1.dylib: stat() failed with errno=1

¥ Johns-MBP.hsd1.or.comcast.net {/Users/johnmccrae} chef --version
Chef Workstation version: 21.2.303
Chef Infra Client version: 16.10.17
Chef InSpec version: 4.26.13
Chef CLI version: 3.1.1
Chef Habitat version: 1.6.181
Test Kitchen version: 2.10.0
Cookstyle version: 7.8.3`

**Comment by tas50** [comment]
This is fixed by disabling libzstd in our curl compilation. Thanks for the heads up @kmf

**Comment by LevonBecker** [comment]
What worked for me was to downgrade to 21.2.278 or Install the development version 21.3.332 (Sticking with this).

**Comment by jeffbyrnes** [comment]
I see a similar error, except it’s with commands provided by Chef Workstation itself:

```bash
♠ chef exec berks install
<internal:/opt/chef-workstation/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': dlopen(/Users/jeffbyrnes/.chef/gem/ruby/3.1.0/gems/stringio-3.1.0/lib/stringio.bundle, 0x0009): tried: '/Users/jeffbyrnes/.chef/gem/ruby/3.1.0/gems/stringio-3.1.0/lib/stringio.bundle' (code signature in <AFE05F8F-C3B2-31F7-9803-067080E2FD9E> '/Users/jeffbyrnes/.chef/gem/ruby/3.1.0/gems/stringio-3.1.0/lib/stringio.bundle' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/System/Volumes/Preboot/Cryptexes/OS/Users/jeffbyrnes/.chef/gem/ruby/3.1.0/gems/stringio-3.1.0/lib/stringio.bundle' (no such file), '/Users/jeffbyrnes/.chef/gem/ruby/3.1.0/gems/stringio-3.1.0/lib/stringio.bundle' (code signature in <AFE05F8F-C3B2-31F7-9803-067080E2FD9E> '/Users/jeffbyrnes/.chef/gem/ruby/3.1.0/gems/stringio-3.1.0/lib/stringio.bundle' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs) - /Users/jeffbyrnes/.chef/gem/ruby/3.1.0/gems/stringio-3.1.0/lib/stringio.bundle (LoadError)
	from <internal:/opt/chef-workstation/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-utils-18.5.0/lib/chef-utils/dsl/train_helpers.rb:18:in `<top (required)>'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-utils-18.5.0/lib/chef-utils/dsl/introspection.rb:19:in `require_relative'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-utils-18.5.0/lib/chef-utils/dsl/introspection.rb:19:in `<top (required)>'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-utils-18.5.0/lib/chef-utils.rb:22:in `require_relative'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-utils-18.5.0/lib/chef-utils.rb:22:in `<top (required)>'
	from <internal:/opt/chef-workstation/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/opt/chef-workstation/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-config-18.5.0/lib/chef-config/path_helper.rb:19:in `<top (required)>'
	from <internal:/opt/chef-workstation/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/opt/chef-workstation/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.5.0/lib/chef/util/path_helper.rb:19:in `<top (required)>'
	from <internal:/opt/chef-workstation/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/opt/chef-workstation/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-cli-5.6.14/lib/chef-cli/cli.rb:25:in `<top (required)>'
	from <internal:/opt/chef-workstation/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/opt/chef-workstation/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-cli-5.6.14/bin/chef-cli:23:in `<top (required)>'
	from /usr/local/bin/chef-cli:440:in `load'
	from /usr/local/bin/chef-cli:440:in `<main>'
```
