### ISSUE TITLE
Windows buildings failing on require 'win32/process'

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation#1893]
In the latest ruby 2.7.3 release we are now seeing failures with win32/process requires on Windows:

```
Using omnibus-software 4.0.0 from https://github.com/chef/omnibus-software.git (at master@56f6321)
Bundle complete! 8 Gemfile dependencies, 45 gems now installed.
Gems in the group development were not installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
C:/opscode/omnibus-toolchain/embedded/lib/ruby/gems/2.6.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout/windows.rb:21:in `require': cannot load such file -- win32/process (LoadError)
	from C:/opscode/omnibus-toolchain/embedded/lib/ruby/gems/2.6.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout/windows.rb:21:in `<top (required)>'
	from C:/opscode/omnibus-toolchain/embedded/lib/ruby/gems/2.6.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout.rb:32:in `require_relative'
	from C:/opscode/omnibus-toolchain/embedded/lib/ruby/gems/2.6.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout.rb:32:in `<class:ShellOut>'
	from C:/opscode/omnibus-toolchain/embedded/lib/ruby/gems/2.6.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout.rb:26:in `<module:Mixlib>'
	from C:/opscode/omnibus-toolchain/embedded/lib/ruby/gems/2.6.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout.rb:24:in `<top (required)>'
	from C:/opscode/omnibus-toolchain/embedded/lib/ruby/gems/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/util.rb:17:in `require'
	from C:/opscode/omnibus-toolchain/embedded/lib/ruby/gems/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/util.rb:17:in `<top (required)>'
	from C:/opscode/omnibus-toolchain/embedded/lib/ruby/gems/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus.rb:25:in `require'
	from C:/opscode/omnibus-toolchain/embedded/lib/ruby/gems/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus.rb:25:in `<top (required)>'
	from C:/opscode/omnibus-toolchain/embedded/lib/ruby/gems/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/cli.rb:18:in `require'
	from C:/opscode/omnibus-toolchain/embedded/lib/ruby/gems/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/cli.rb:18:in `<top (required)>'
	from C:/opscode/omnibus-toolchain/embedded/lib/ruby/gems/2.6.0/bundler/gems/omnibus-dd5789621fa3/bin/omnibus:10:in `require'
	from C:/opscode/omnibus-toolchain/embedded/lib/ruby/gems/2.6.0/bundler/gems/omnibus-dd5789621fa3/bin/omnibus:10:in `<top (required)>'
	from C:/opscode/omnibus-toolchain/embedded/lib/ruby/gems/2.6.0/bin/omnibus:23:in `load'
	from C:/opscode/omnibus-toolchain/embedded/lib/ruby/gems/2.6.0/bin/omnibus:23:in `<main>'
[31m🚨 Error: The command exited with status 1[0m
```

See https://buildkite.com/chef/chef-chef-workstation-master-omnibus-release/builds/720#2c5f5426-1ec5-4816-871e-ead8eef1485e

**Comment by tas50** [comment]
This was fixed by added the windows deps back to the omnibus lock. Dependabot broke this
