### ISSUE TITLE
macOS builds failing on Ruby 2.7.3

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation#1894]
This new failure is showing up post upgrade to Ruby 2.7.3.

```
configure.ac:303: warning: The macro `AC_HELP_STRING' is obsolete.

configure.ac:303: You should run autoupdate.

./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...

gecode.m4:400: AC_GECODE_ENABLE_MODULE is expanded from...

configure.ac:303: the top level

./config.status --recheck

running CONFIG_SHELL=/bin/sh /bin/sh

/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/dep-selector-libgecode-1.3.5/ext/libgecode3/vendor/gecode-3.7.3/configure

--prefix=/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/dep-selector-libgecode-1.3.5/lib/dep-selector-libgecode/vendored-gecode

--disable-doc-dot --disable-doc-search --disable-doc-tagfile --disable-doc-chm

--disable-doc-docset --disable-qt --disable-examples --disable-flatzinc

CXXFLAGS=-I/opt/chef-workstation/embedded/include -O3 -D_FORTIFY_SOURCE=2

-fstack-protector LDFLAGS=-Wl,-rpath,/opt/chef-workstation/embedded/lib

-L/opt/chef-workstation/embedded/lib

CPPFLAGS=-I/opt/chef-workstation/embedded/include -O3 -D_FORTIFY_SOURCE=2

-fstack-protector CFLAGS=-I/opt/chef-workstation/embedded/include -O3

-D_FORTIFY_SOURCE=2 -fstack-protector --no-create --no-recursion

configure: error: cannot find required auxiliary files: config.guess config.sub

make: *** [Makefile:1457: config.status] Error 1

extconf.rb:124:in `block in run': Failed to build gecode library.

(GecodeBuild::BuildError)

	from extconf.rb:123:in `chdir'

	from extconf.rb:123:in `run'

	from extconf.rb:130:in `<main>'



extconf failed, exit code 1



Gem files will remain installed in

/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/dep-selector-libgecode-1.3.5

for inspection.

Results logged to

/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/extensions/x86_64-darwin-18/2.7.0/dep-selector-libgecode-1.3.5/gem_make.out



An error occurred while installing dep-selector-libgecode (1.3.5), and Bundler

cannot continue.

Make sure that `gem install dep-selector-libgecode -v '1.3.5' --source

'https://rubygems.org/'` succeeds before bundling.



In Gemfile:

  dep_selector was resolved to 1.0.6, which depends on

    dep-selector-libgecode



/Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/util.rb:139:in `rescue in shellout!'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/util.rb:134:in `shellout!'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/builder.rb:871:in `shellout!'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/builder.rb:355:in `block in bundle'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/builder.rb:1061:in `instance_eval'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/builder.rb:1061:in `run'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/builder.rb:889:in `block (3 levels) in execute'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/builder.rb:911:in `with_retries'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/builder.rb:888:in `block (2 levels) in execute'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/instrumentation.rb:23:in `measure'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/builder.rb:887:in `block in execute'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/builder.rb:962:in `with_clean_env'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/builder.rb:886:in `execute'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/builder.rb:778:in `block (2 levels) in build'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/builder.rb:777:in `each'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/builder.rb:777:in `block in build'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/instrumentation.rb:23:in `measure'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/builder.rb:776:in `build'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/software.rb:1224:in `execute_build'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/software.rb:1112:in `build_me'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/project.rb:1078:in `block (2 levels) in build'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/project.rb:1077:in `each'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/project.rb:1077:in `block in build'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/licensing.rb:62:in `block in create_incrementally'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/licensing.rb:57:in `tap'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/licensing.rb:57:in `create_incrementally'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/project.rb:1076:in `build'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/cli.rb:89:in `build'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/cli/base.rb:33:in `dispatch'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/lib/omnibus/cli.rb:42:in `execute!'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-dd5789621fa3/bin/omnibus:16:in `<top (required)>'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bin/omnibus:23:in `load'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bin/omnibus:23:in `<top (required)>'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:63:in `load'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:63:in `kernel_load'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:28:in `run'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:476:in `exec'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:30:in `dispatch'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:24:in `start'

  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'

  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'

  /opt/omnibus-toolchain/bin/bundle:23:in `load'

  /opt/omnibus-toolchain/bin/bundle:23:in `<main>'

[31m🚨 Error: The command exited with status 1[0m
^^^ +++
```

see: https://buildkite.com/chef/chef-chef-workstation-master-omnibus-release/builds/720#e9c31a73-d5ff-4d09-a34d-5e247e84dbf0

**Comment by nikhil2611** [comment]
Fixed.
