### ISSUE TITLE
macOS builds failing with git error

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation#1978]
```
           [GitCache: go] I | 2021-05-10T10:36:37-07:00 | $ git -c core.autocrlf=false -c core.ignorecase=false --git-dir="/var/cache/omnibus/chef-workstation/cache/git_cache/opt/chef-workstation" --work-tree="/opt/chef-workstation" add -A -f

                          I | 2021-05-10T10:36:37-07:00 | fatal: iconv_open(UTF-8,UTF-8-MAC) failed, but needed:

                          I | 2021-05-10T10:36:37-07:00 |     precomposed unicode is not supported.

                          I | 2021-05-10T10:36:37-07:00 |     If you want to use decomposed unicode, run

                          I | 2021-05-10T10:36:37-07:00 |     "git config core.precomposeunicode false"

                          I | 2021-05-10T10:36:37-07:00 | 

The following shell command exited with status 128:



    $ git -c core.autocrlf=false -c core.ignorecase=false --git-dir="/var/cache/omnibus/chef-workstation/cache/git_cache/opt/chef-workstation" --work-tree="/opt/chef-workstation" add -A -f



Output:



    (nothing)



Error:



    fatal: iconv_open(UTF-8,UTF-8-MAC) failed, but needed:

    precomposed unicode is not supported.

    If you want to use decomposed unicode, run

    "git config core.precomposeunicode false"



/Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/util.rb:139:in `rescue in shellout!'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/util.rb:134:in `shellout!'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/git_cache.rb:199:in `git_cmd'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/git_cache.rb:130:in `incremental'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/software.rb:1228:in `execute_build'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/software.rb:1102:in `build_me'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/project.rb:1078:in `block (2 levels) in build'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/project.rb:1077:in `each'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/project.rb:1077:in `block in build'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/licensing.rb:62:in `block in create_incrementally'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/licensing.rb:57:in `tap'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/licensing.rb:57:in `create_incrementally'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/project.rb:1076:in `build'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/cli.rb:89:in `build'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/cli/base.rb:33:in `dispatch'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-87db446ee0b9/lib/omnibus/cli.rb:42:in `execute!'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bundler/gems/omnibus-87db446ee0b9/bin/omnibus:16:in `<top (required)>'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bin/omnibus:23:in `load'

  /Users/anka/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/bin/omnibus:23:in `<top (required)>'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:63:in `load'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:63:in `kernel_load'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:28:in `run'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:476:in `exec'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:30:in `dispatch'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:24:in `start'

  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'

  /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'

  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'

  /opt/omnibus-toolchain/bin/bundle:23:in `load'

  /opt/omnibus-toolchain/bin/bundle:23:in `<main>'

[31m🚨 Error: The command exited with status 1[0m

```

**Comment by tas50** [comment]
This has magically resolved itself
