### ISSUE TITLE
knife issues in Chef Workstation 21.5.420

### ISSUE THREAD

**Issue by jtonello** [chef/chef-workstation#1979]
## Description
knife commands fail, including knife ssl fetch and knife configure init-config
```
jtonello@ip-172-31-81-191:~/.chef$ knife configure init-config -VVV
Traceback (most recent call last):
	10: from /bin/knife:357:in `<main>'
	 9: from /bin/knife:357:in `load'
	 8: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.0.246/bin/knife:24:in `<top (required)>'
	 7: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.0.246/lib/chef/application/knife.rb:165:in `run'
	 6: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.0.246/lib/chef/knife.rb:233:in `run'
	 5: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.0.246/lib/chef/knife.rb:493:in `run_with_pretty_exceptions'
	 4: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-17.0.242/lib/chef/local_mode.rb:42:in `with_server_connectivity'
	 3: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.0.246/lib/chef/knife.rb:494:in `block in run_with_pretty_exceptions'
	 2: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.0.246/lib/chef/knife/configure.rb:76:in `run'
	 1: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.0.246/lib/chef/knife/configure.rb:117:in `ask_user_for_config'
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.0.246/lib/chef/knife/configure.rb:134:in `guess_servername': uninitialized constant Ohai::System (NameError)
```
And
```
jtonello@ip-172-31-81-191:~$ knife ssl fetch
Traceback (most recent call last):
	9: from /bin/knife:357:in `<main>'
	8: from /bin/knife:357:in `load'
	7: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.0.246/bin/knife:24:in `<top (required)>'
	6: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.0.246/lib/chef/application/knife.rb:165:in `run'
	5: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.0.246/lib/chef/knife.rb:230:in `run'
	4: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.0.246/lib/chef/knife.rb:245:in `load_deps'
	3: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.0.246/lib/chef/knife.rb:245:in `each'
	2: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.0.246/lib/chef/knife/ssl_fetch.rb:31:in `block in <class:SslFetch>'
	1: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- chef/mixin/mixin/proxified_socket (LoadError)
jtonello@ip-172-31-81-191:~$ 
```
## Chef Workstation Version
21.5.420

## Platform Version
Ubuntu 20.04 (desktop)

**Comment by collinmcneese** [comment]
`knife list` and `knife show` commands are also not working in this release:

```
$ knife list policies
ERROR: knife encountered an unexpected error
This may be a bug in the 'list' knife command or plugin
Please collect the output of this command with the `-VVV` option before filing a bug report.
Exception: NoMethodError: undefined method `parallel_map' for #<Array:0x00007f96f5bdc5e8>

$ knife show policies
ERROR: knife encountered an unexpected error
This may be a bug in the 'show' knife command or plugin
Please collect the output of this command with the `-VVV` option before filing a bug report.
Exception: NoMethodError: undefined method `parallel_map' for #<Array:0x00007fa10fb23380>

$ knife --version
Chef Infra Client: 17.0.242
```

**Comment by Dylan-M** [comment]
I recently fixed the `knife ssl fetch` command, and my fix was accepted. So that will be fixed in next release.
Issue [#11580](https://github.com/chef/chef/issues/11580)
Fixed by [#11581](https://github.com/chef/chef/pull/11581)

**Comment by Dylan-M** [comment]
I'm also facing the issues with `parallel_map` and `parallel_each` that are documented in this bug report. Would be nice to see this fixed. :)

**Comment by Dylan-M** [comment]
@lamont-granquist This is another one that I'm guessing is related to the Ruby 2.7 vs 3.0 issue you were discussing in the other bug I just responded to.

**Comment by tas50** [comment]
The main issue here is resolved in the latest release and the later issue discussed is being worked in our PR to bump to Ruby 3
