### ISSUE TITLE
First run does not create ~/.chef-workstation

### ISSUE THREAD

**Issue by jvogt** [chef/chef-workstation#200]
## Chef Workstation Version
0.1.133

## Platform Version
macOS 10.13.5

## Replication Case
On a fresh first-time install running chef-run complains about `~/.chef-workstation/config.toml`  not existing
```
$ chef-run ubuntu1 directory /tmp/foo
Creating config file in /Users/jvogt/.chef-workstation/config.toml.

Traceback (most recent call last):
  11: from /usr/local/bin/chef-run:179:in `<main>'
  10: from /usr/local/bin/chef-run:179:in `load'
   9: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-run-0.1.133/bin/chef-run:23:in `<top (required)>'
   8: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-run-0.1.133/lib/chef-run/startup.rb:36:in `run'
   7: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-run-0.1.133/lib/chef-run/startup.rb:89:in `first_run_tasks'
   6: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-run-0.1.133/lib/chef-run/startup.rb:96:in `create_default_config'
   5: from /opt/chef-workstation/embedded/lib/ruby/2.5.0/fileutils.rb:1051:in `touch'
   4: from /opt/chef-workstation/embedded/lib/ruby/2.5.0/fileutils.rb:1051:in `each'
   3: from /opt/chef-workstation/embedded/lib/ruby/2.5.0/fileutils.rb:1053:in `block in touch'
   2: from /opt/chef-workstation/embedded/lib/ruby/2.5.0/fileutils.rb:1057:in `rescue in block in touch'
   1: from /opt/chef-workstation/embedded/lib/ruby/2.5.0/fileutils.rb:1057:in `open'
/opt/chef-workstation/embedded/lib/ruby/2.5.0/fileutils.rb:1057:in `initialize': No such file or directory @ rb_sysopen - /Users/jvogt/.chef-workstation/config.toml (Errno::ENOENT)
```
Resolution is to manually create the `~/.chef-workstation` directory:
```
$ mkdir ~/.chef-workstation
$ chef-run ubuntu1 directory /tmp/foo
[✔] [ubuntu1] Connected.
...
```
Running 0.1.133
```
$ chef-run --version
chef-run: 0.1.133
```

**Comment by jvogt** [comment]
Nevermind, I see a merged PR for this issue.  Closing.
