### ISSUE TITLE
SSH key configuration no longer read from ~/.ssh/config

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-workstation#202]
## Description
When Chef Workstation launched I could add configuration similar to the following to my `~/.ssh/config`:
```sh
Host 192.168.33.51 ubuntu1
     IdentityFile /Users/tball/.ssh/new_key
```

When I ran `chef-run user@ubuntu1` it would correctly read my configuration and I did not need to supply my key. It no longer does this.

This used to be a problem only with released version of our package and I could get it to successfully work from source with `bundle exec`. But this is no longer the case.

## Chef Workstation Version
master

## Platform Version
OSX

## Stacktrace
```
2018-06-18 16:02:59 -0600: Error encountered while running the following:
  vagrant@ubuntu1 directory /tmp/foo
Backtrace:
Train::Transports::SSHFailed: SSH session could not be established
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/bundler/gems/train-daefae3357bd/lib/train/transports/ssh_connection.rb:157:in `rescue in establish_connection'
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/bundler/gems/train-daefae3357bd/lib/train/transports/ssh_connection.rb:146:in `establish_connection'
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/bundler/gems/train-daefae3357bd/lib/train/transports/ssh_connection.rb:236:in `session'
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/bundler/gems/train-daefae3357bd/lib/train/transports/ssh_connection.rb:191:in `run_command_via_connection'
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/bundler/gems/train-daefae3357bd/lib/train/plugins/base_connection.rb:108:in `run_command'
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/bundler/gems/train-daefae3357bd/lib/train/platforms/detect/helpers/os_common.rb:36:in `command_output'
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/bundler/gems/train-daefae3357bd/lib/train/platforms/detect/helpers/os_common.rb:43:in `unix_uname_s'
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/bundler/gems/train-daefae3357bd/lib/train/platforms/detect/specifications/os.rb:35:in `block in load'
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/bundler/gems/train-daefae3357bd/lib/train/platforms/detect/scanner.rb:46:in `instance_eval'
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/bundler/gems/train-daefae3357bd/lib/train/platforms/detect/scanner.rb:46:in `block in scan_children'
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/bundler/gems/train-daefae3357bd/lib/train/platforms/detect/scanner.rb:45:in `each'
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/bundler/gems/train-daefae3357bd/lib/train/platforms/detect/scanner.rb:45:in `scan_children'
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/bundler/gems/train-daefae3357bd/lib/train/platforms/detect/scanner.rb:33:in `block in scan'
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/bundler/gems/train-daefae3357bd/lib/train/platforms/detect/scanner.rb:27:in `each'
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/bundler/gems/train-daefae3357bd/lib/train/platforms/detect/scanner.rb:27:in `scan'
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/bundler/gems/train-daefae3357bd/lib/train/platforms/detect.rb:9:in `scan'
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/bundler/gems/train-daefae3357bd/lib/train/plugins/base_connection.rb:100:in `platform'
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/bundler/gems/train-daefae3357bd/lib/train/extras/command_wrapper.rb:128:in `load'
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/bundler/gems/train-daefae3357bd/lib/train/transports/ssh_connection.rb:46:in `initialize'
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/bundler/gems/train-daefae3357bd/lib/train/transports/ssh.rb:196:in `new'
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/bundler/gems/train-daefae3357bd/lib/train/transports/ssh.rb:196:in `create_new_connection'
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/bundler/gems/train-daefae3357bd/lib/train/transports/ssh.rb:76:in `connection'
        /Users/tball/github/chef-workstation/components/chef-run/lib/chef-run/target_host.rb:55:in `connect!'
        /Users/tball/github/chef-workstation/components/chef-run/lib/chef-run/cli.rb:404:in `do_connect'
        /Users/tball/github/chef-workstation/components/chef-run/lib/chef-run/cli.rb:139:in `block in connect_target'
        /Users/tball/github/chef-workstation/components/chef-run/lib/chef-run/ui/terminal.rb:83:in `block in render_job'
        /Users/tball/github/chef-workstation/components/chef-run/lib/chef-run/ui/plain_text_element.rb:28:in `run'
        /Users/tball/github/chef-workstation/components/chef-run/lib/chef-run/ui/terminal.rb:83:in `render_job'
        /Users/tball/github/chef-workstation/components/chef-run/lib/chef-run/cli.rb:138:in `connect_target'
        /Users/tball/github/chef-workstation/components/chef-run/lib/chef-run/cli.rb:149:in `run_single_target'
        /Users/tball/github/chef-workstation/components/chef-run/lib/chef-run/cli.rb:114:in `perform_run'
        /Users/tball/github/chef-workstation/components/chef-run/lib/chef-run/cli.rb:63:in `block in run'
        /Users/tball/github/chef-workstation/components/chef-run/lib/chef-run/telemeter.rb:85:in `block in timed_capture'
        /Users/tball/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
        /Users/tball/github/chef-workstation/components/chef-run/lib/chef-run/telemeter.rb:85:in `timed_capture'
        /Users/tball/github/chef-workstation/components/chef-run/lib/chef-run/telemeter.rb:74:in `timed_run_capture'
        /Users/tball/github/chef-workstation/components/chef-run/lib/chef-run/cli.rb:61:in `run'
        /Users/tball/github/chef-workstation/components/chef-run/lib/chef-run/startup.rb:152:in `start_chef_run'
        /Users/tball/github/chef-workstation/components/chef-run/lib/chef-run/startup.rb:56:in `run'
        /Users/tball/github/chef-workstation/components/chef-run/bin/chef-run:23:in `<top (required)>'
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/bin/chef-run:23:in `load'
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/bin/chef-run:23:in `<main>'
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/bin/ruby_executable_hooks:15:in `eval'
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/bin/ruby_executable_hooks:15:in `<main>'
Caused by: Net::SSH::AuthenticationFailed: Authentication failed for user vagrant@192.168.33.51
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/gems/net-ssh-4.2.0/lib/net/ssh.rb:254:in `start'
        /Users/tball/.rvm/gems/ruby-2.5.1@chef-workstation/bundler/gems/train-daefae3357bd/lib/train/transports/ssh_connection.rb:153:in `establish_connection'
        ... 42 more
```

**Comment by marcparadise** [comment]
This looks like the side effect of #176 - because we now always populate this into the target URL, the missing values in the identity portion get mapped to empty strings instead of nils.   I'd been thinking anyway about changing the behavior to always use the train options map, and do not use the URL form except to resolve protocol.   That should fix this behavior, without regressing #175 (which was fixed by #176)

**Comment by marcparadise** [comment]
This is being tracked internally as SHACK-252

**Comment by kmf** [comment]
Thanks for all the effort.

**Comment by marcparadise** [comment]
An partial  fix is in place for this with #212 - but username will still default to 'root' even if .ssh/config has a  User directive for the host - this will need to be fixed in train. We're looking into that now. 
I'll keep this open until that is resolved as well.

**Comment by marcparadise** [comment]
Related: https://github.com/inspec/train/issues/101 - I didn't verify port, but a quick look through train says that it still won't get picked up from config. It's got the same situation that 'user' does - it has a default in train, and if you don't provide it the default will be used. This prevents net/ssh from extracting it from config - its default behavior for these fields when values are not given.

**Comment by tyler-ball** [comment]
I think we fixed this with workarounds, so closing for now. Any upstream bugs we should track in the upstream repo
