### ISSUE TITLE
WinRM connections only work under 'bundle exec'

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-workstation#204]
## Description
I can get `chef-run` to manage an ad-hoc remote Windows node only if I `bundle exec chef-run`. The built packages do not appear to work.

## Chef Workstation Version
master / 0.1.135

## Platform Version
OSX workstation, Windows target

## Replication Case

1. Create an EC2 Windows `Windows_Server-2016-English-Core-Base` host 
1. In the user data for this host set a user and password with something like
```
net user /y /add chefws SomePasswordThatIsLong!!!
net localgroup Administrators /add chefws
```
The long password and exclamation points are required for the password security requirements
1. Get the IP address of the host from the EC2 console
1. Execute something like `chef-run 'winrm://ec2user:SomePasswordThatIsLong!!!@127.0.0.1:5985' directory /tmp`
1. The command will not successfully connect to the host
1. Check out master and `bundle install`
1. `bundle exec chef-run 'winrm://ec2user:SomePasswordThatIsLong!!!@127.0.0.1:5985' directory /tmp`

Unfortunately this looks to be transient behavior - a very few times it did succeed using the installed package. I thought this was because it would work against the local vagrant Windows image and fail against the remote EC2 vagrant image, but this does not appear to be the case. It was actually just transiently succeeding.

It takes quite a long time for it to timeout with the `WinRM::WinRMAuthorizationError`

## Client Output

```
[ - ] Generating local policyfile...
[ - ] Generated local policyfile
[ - ] [127.0.0.1] Connecting...
[ - ] [127.0.0.1] WinRM::WinRMAuthorizationError

CHEFINT001

An unexpected error has occurred:

  WinRM::WinRMAuthorizationError

If you are not able to resolve this issue, please contact Chef support
at beta@chef.io and include the log file and stack trace from the
locations below:

  /Users/tball/.chef-workstation/logs/default.log
  /Users/tball/.chef-workstation/logs/stack-trace.log
```

## Stacktrace

```
2018-06-18 16:59:37 -0600: Error encountered while running the following:
  winrm://vagrant:1234567890abcdefg!!!@127.0.0.1:5985 /Users/tball/github/chefws-chef-conf/cookbooks/my_nginx/recipes/dep.rb
Backtrace:
WinRM::WinRMAuthorizationError: WinRM::WinRMAuthorizationError
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/winrm-2.2.3/lib/winrm/http/response_handler.rb:58:in `raise_if_auth_error'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/winrm-2.2.3/lib/winrm/http/response_handler.rb:51:in `raise_if_error'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/winrm-2.2.3/lib/winrm/http/response_handler.rb:36:in `parse_to_xml'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/winrm-2.2.3/lib/winrm/http/transport.rb:186:in `send_request'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/winrm-2.2.3/lib/winrm/http/transport.rb:181:in `send_request'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/winrm-2.2.3/lib/winrm/shells/power_shell.rb:152:in `max_envelope_size_kb'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/winrm-2.2.3/lib/winrm/shells/power_shell.rb:80:in `max_fragment_blob_size'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/winrm-2.2.3/lib/winrm/shells/power_shell.rb:198:in `fragmenter'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/winrm-2.2.3/lib/winrm/shells/power_shell.rb:162:in `block in open_shell_payload'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/winrm-2.2.3/lib/winrm/shells/power_shell.rb:161:in `map'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/winrm-2.2.3/lib/winrm/shells/power_shell.rb:161:in `open_shell_payload'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/winrm-2.2.3/lib/winrm/shells/power_shell.rb:122:in `open_shell'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/winrm-2.2.3/lib/winrm/shells/base.rb:168:in `block in open'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/winrm-2.2.3/lib/winrm/shells/retryable.rb:37:in `retryable'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/winrm-2.2.3/lib/winrm/shells/base.rb:166:in `open'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/winrm-2.2.3/lib/winrm/shells/base.rb:129:in `with_command_shell'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/winrm-2.2.3/lib/winrm/shells/base.rb:81:in `run'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/train-1.4.4/lib/train/transports/winrm_connection.rb:103:in `run_command_via_connection'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/train-1.4.4/lib/train/transports/winrm_connection.rb:83:in `wait_until_ready'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-run-0.1.135/lib/chef-run/target_host.rb:56:in `connect!'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-run-0.1.135/lib/chef-run/cli.rb:501:in `do_connect'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-run-0.1.135/lib/chef-run/cli.rb:236:in `block in connect_target'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-run-0.1.135/lib/chef-run/ui/terminal.rb:83:in `block in render_job'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-run-0.1.135/lib/chef-run/ui/plain_text_element.rb:28:in `run'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-run-0.1.135/lib/chef-run/ui/terminal.rb:83:in `render_job'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-run-0.1.135/lib/chef-run/cli.rb:235:in `connect_target'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-run-0.1.135/lib/chef-run/cli.rb:246:in `run_single_target'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-run-0.1.135/lib/chef-run/cli.rb:211:in `perform_run'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-run-0.1.135/lib/chef-run/cli.rb:160:in `block in run'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-run-0.1.135/lib/chef-run/telemeter.rb:85:in `block in timed_capture'
        /opt/chef-workstation/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-run-0.1.135/lib/chef-run/telemeter.rb:85:in `timed_capture'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-run-0.1.135/lib/chef-run/telemeter.rb:74:in `timed_run_capture'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-run-0.1.135/lib/chef-run/cli.rb:158:in `run'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-run-0.1.135/lib/chef-run/startup.rb:151:in `start_chef_run'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-run-0.1.135/lib/chef-run/startup.rb:56:in `run'
        /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-run-0.1.135/bin/chef-run:23:in `<top (required)>'
        /usr/local/bin/chef-run:179:in `load'
        /usr/local/bin/chef-run:179:in `<main>'

```

**Comment by tyler-ball** [comment]
This is no longer an issue in the latest Chef Workstation release (chef-apply version `0.1.21`). I can correctly connect from a local OSX workstation to a vagrant WinRM host.

No idea about Windows host -> Windows target
