### ISSUE TITLE
Chef Workstation in FIPS mode errors when running Test Kitchen to Windows platform targets

### ISSUE THREAD

**Issue by collinmcneese** [chef/chef-workstation#2111]
## Description

When running Chef Workstation in FIPS mode from an EL7 system, the error `Digest initialization failed: disabled for fips` is encountered when running with specific criteria:

* Chef Workstation is running in FIPS mode on a FIPS-enabled instance (EL7 in this case)
* Test Kitchen is using a target platform which is Windows (FIPS-enabled or not)
* Cookbook which is being tested is using Berkshelf for dependency resolution instead of `Policyfile.rb`

All other tested scenarios appear to work without issue, but when the three criteria above are met, the error `Digest initialization failed: disabled for fips` will appear.

As a workaround, adding `CHEF_FIPS=''` to the env does seem to work to converge successfully but that does not fix the underlying cause and requires automated pipelines to have this set, including those which should be operating in an environment where FIPS is enforced.

Small version of the error:
```
kitchen converge default-windows
-----> Starting Test Kitchen (v2.12.0)
-----> Converging <default-windows>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 7.2.2...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [Digest initialization failed: disabled for fips] on default-windows
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Larger version with debug information:
```
D      [WinRM] opening remote shell on http://ec2-34-219-102-XXX.us-west-2.compute.amazonaws.com:5985/wsman
D      Cleaning up local sandbox in /tmp/default-windows-sandbox-20210701-8090-lmr27w
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [Digest initialization failed: disabled for fips] on default-windows
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [Digest initialization failed: disabled for fips] on default-windows
D      ----------------------
D      ------Backtrace-------
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/command.rb:181:in `report_errors'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/command.rb:172:in `run_action'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/command/action.rb:35:in `block in call'
D      /opt/chef-workstation/embedded/lib/ruby/3.0.0/benchmark.rb:293:in `measure'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/command/action.rb:33:in `call'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/cli.rb:52:in `perform'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/cli.rb:198:in `block (2 levels) in <class:CLI>'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/bin/kitchen:11:in `block in <top (required)>'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/errors.rb:170:in `with_friendly_errors'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/bin/kitchen:11:in `<top (required)>'
D      /bin/kitchen:360:in `load'
D      /bin/kitchen:360:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #converge action: [Digest initialization failed: disabled for fips] on default-windows
D      ----------------------
D      ------Backtrace-------
D      /opt/chef-workstation/embedded/lib/ruby/3.0.0/openssl/digest.rb:35:in `initialize'
D      /opt/chef-workstation/embedded/lib/ruby/3.0.0/openssl/digest.rb:35:in `block (3 levels) in <class:Digest>'
D      /opt/chef-workstation/embedded/lib/ruby/3.0.0/openssl/digest.rb:41:in `new'
D      /opt/chef-workstation/embedded/lib/ruby/3.0.0/openssl/digest.rb:41:in `block (3 levels) in <class:Digest>'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/rubyntlm-0.6.3/lib/net/ntlm.rb:149:in `ntlm_hash'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/rubyntlm-0.6.3/lib/net/ntlm.rb:162:in `ntlmv2_hash'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/rubyntlm-0.6.3/lib/net/ntlm/client/session.rb:192:in `ntlmv2_hash'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/rubyntlm-0.6.3/lib/net/ntlm/client/session.rb:196:in `calculate_user_session_key!'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/rubyntlm-0.6.3/lib/net/ntlm/client/session.rb:27:in `authenticate!'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/rubyntlm-0.6.3/lib/net/ntlm/client.rb:36:in `init_context'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/http/transport.rb:244:in `init_auth'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/http/transport.rb:168:in `send_request'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:153:in `max_envelope_size_kb'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:78:in `max_fragment_blob_size'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:203:in `fragmenter'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:167:in `block in open_shell_payload'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:166:in `map'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:166:in `open_shell_payload'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:123:in `open_shell'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/base.rb:170:in `block in open'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/retryable.rb:35:in `retryable'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/base.rb:168:in `open'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/base.rb:128:in `with_command_shell'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/base.rb:79:in `run'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/transport/winrm.rb:257:in `execute_with_exit_code'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/transport/winrm.rb:108:in `execute'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/provisioner/base.rb:80:in `block in call'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/transport/base.rb:100:in `initialize'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/transport/winrm.rb:87:in `initialize'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/transport/winrm.rb:477:in `new'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/transport/winrm.rb:477:in `create_new_connection'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/transport/winrm.rb:74:in `connection'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/provisioner/base.rb:75:in `call'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/instance.rb:419:in `block in converge_action'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/instance.rb:563:in `synchronize_or_call'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/instance.rb:524:in `block in action'
D      /opt/chef-workstation/embedded/lib/ruby/3.0.0/benchmark.rb:293:in `measure'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/instance.rb:523:in `action'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/instance.rb:414:in `converge_action'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/instance.rb:392:in `block (2 levels) in transition_to'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/lifecycle_hooks.rb:47:in `run_with_hooks'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/instance.rb:391:in `block in transition_to'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/instance.rb:390:in `each'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/instance.rb:390:in `transition_to'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/instance.rb:139:in `converge'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/command.rb:195:in `public_send'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/command.rb:195:in `run_action_in_thread'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/command.rb:166:in `block (2 levels) in run_action'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #converge action: [Digest initialization failed: disabled for fips]
D      ----------------------
D      ------Backtrace-------
D      /opt/chef-workstation/embedded/lib/ruby/3.0.0/openssl/digest.rb:35:in `initialize'
D      /opt/chef-workstation/embedded/lib/ruby/3.0.0/openssl/digest.rb:35:in `block (3 levels) in <class:Digest>'
D      /opt/chef-workstation/embedded/lib/ruby/3.0.0/openssl/digest.rb:41:in `new'
D      /opt/chef-workstation/embedded/lib/ruby/3.0.0/openssl/digest.rb:41:in `block (3 levels) in <class:Digest>'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/rubyntlm-0.6.3/lib/net/ntlm.rb:149:in `ntlm_hash'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/rubyntlm-0.6.3/lib/net/ntlm.rb:162:in `ntlmv2_hash'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/rubyntlm-0.6.3/lib/net/ntlm/client/session.rb:192:in `ntlmv2_hash'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/rubyntlm-0.6.3/lib/net/ntlm/client/session.rb:196:in `calculate_user_session_key!'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/rubyntlm-0.6.3/lib/net/ntlm/client/session.rb:27:in `authenticate!'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/rubyntlm-0.6.3/lib/net/ntlm/client.rb:36:in `init_context'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/http/transport.rb:244:in `init_auth'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/http/transport.rb:168:in `send_request'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:153:in `max_envelope_size_kb'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:78:in `max_fragment_blob_size'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:203:in `fragmenter'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:167:in `block in open_shell_payload'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:166:in `map'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:166:in `open_shell_payload'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:123:in `open_shell'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/base.rb:170:in `block in open'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/retryable.rb:35:in `retryable'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/base.rb:168:in `open'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/base.rb:128:in `with_command_shell'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/base.rb:79:in `run'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/transport/winrm.rb:257:in `execute_with_exit_code'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/transport/winrm.rb:108:in `execute'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/provisioner/base.rb:80:in `block in call'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/transport/base.rb:100:in `initialize'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/transport/winrm.rb:87:in `initialize'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/transport/winrm.rb:477:in `new'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/transport/winrm.rb:477:in `create_new_connection'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/transport/winrm.rb:74:in `connection'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/provisioner/base.rb:75:in `call'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/instance.rb:419:in `block in converge_action'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/instance.rb:563:in `synchronize_or_call'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/instance.rb:524:in `block in action'
D      /opt/chef-workstation/embedded/lib/ruby/3.0.0/benchmark.rb:293:in `measure'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/instance.rb:523:in `action'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/instance.rb:414:in `converge_action'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/instance.rb:392:in `block (2 levels) in transition_to'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/lifecycle_hooks.rb:47:in `run_with_hooks'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/instance.rb:391:in `block in transition_to'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/instance.rb:390:in `each'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/instance.rb:390:in `transition_to'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/instance.rb:139:in `converge'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/command.rb:195:in `public_send'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/command.rb:195:in `run_action_in_thread'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-2.12.0/lib/kitchen/command.rb:166:in `block (2 levels) in run_action'
D      /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D      ----End Backtrace-----

```

|

**Comment by sanga1794** [comment]
Hi @collinmcneese , To reproduce the issue i created the instance(rhel8) on AWS, installed the chef-workstation on it. and tried to run the command `kitchen converge default-windows` but facing below issue:
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider virtualbox ----
STDOUT: 
STDERR: ==> vagrant: A new version of Vagrant is available: 2.2.18 (installed version: 2.2.17)!
==> vagrant: To upgrade visit: https://www.vagrantup.com/downloads.html

The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

VirtualBox is complaining that the kernel module is not loaded. Please
run `VBoxManage --version` or open the VirtualBox GUI to see the error
message which should contain instructions on how to fix this error.
---- End output of vagrant up --no-provision --provider virtualbox ----
Ran vagrant up --no-provision --provider virtualbox returned 1] on default-windows-10
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
Do you know anything i'm missing while setup?

**Comment by collinmcneese** [comment]
Hi @sanga1794  -- I have not tried with Vagrant/Virtualbox configuration on a FIPS enabled system, there might be some other nuances there, are you attempting to run virtualbox from within virtualbox perhaps?

For the mockups that I was working with, I was using a local CentOS 7 VM but then using the `kitchen-ec2` driver for test kitchen itself, that might be a bit easier to work with?

**Comment by ashiqueps** [comment]
Hi All,

This is an issue with the `winrm/rubyntlm` gem. It is using the FIPS non-compliant algorithms in the codebase and it causing the above exception. Created a new issue in the repo to handle that.
