### ISSUE TITLE
OpenSSL::SSL::SSLError (certificate has expired)

### ISSUE THREAD

**Issue by n-rodriguez** [chef/chef-workstation#2318]
## Description

 ```sh
 OpenSSL::SSL::SSLError: SSL Error connecting to https://www.postgresql.org/media/keys/ACCC4CF8.asc - SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)
```
I think it's related to : https://scotthelme.co.uk/lets-encrypt-old-root-expiration/ (or https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/ ?)

Because the SSL cert is valid : https://www.sslshopper.com/ssl-checker.html#hostname=www.postgresql.org

But Chef Workstation embeds its own CA certs in `/opt/chef-workstation/embedded/ssl/cert.pem`

and `DST Root CA X3` is expired :

```sh
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            44:af:b0:80:d6:a3:27:ba:89:30:39:86:2e:f8:40:6b
        Signature Algorithm: sha1WithRSAEncryption
        Issuer: O = Digital Signature Trust Co., CN = DST Root CA X3
        Validity
            Not Before: Sep 30 21:12:19 2000 GMT
            Not After : Sep 30 14:01:15 2021 GMT
        Subject: O = Digital Signature Trust Co., CN = DST Root CA X3
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:df:af:e9:97:50:08:83:57:b4:cc:62:65:f6:90:
                    82:ec:c7:d3:2c:6b:30:ca:5b:ec:d9:c3:7d:c7:40:
                    c1:18:14:8b:e0:e8:33:76:49:2a:e3:3f:21:49:93:
                    ac:4e:0e:af:3e:48:cb:65:ee:fc:d3:21:0f:65:d2:
                    2a:d9:32:8f:8c:e5:f7:77:b0:12:7b:b5:95:c0:89:
                    a3:a9:ba:ed:73:2e:7a:0c:06:32:83:a2:7e:8a:14:
                    30:cd:11:a0:e1:2a:38:b9:79:0a:31:fd:50:bd:80:
                    65:df:b7:51:63:83:c8:e2:88:61:ea:4b:61:81:ec:
                    52:6b:b9:a2:e2:4b:1a:28:9f:48:a3:9e:0c:da:09:
                    8e:3e:17:2e:1e:dd:20:df:5b:c6:2a:8a:ab:2e:bd:
                    70:ad:c5:0b:1a:25:90:74:72:c5:7b:6a:ab:34:d6:
                    30:89:ff:e5:68:13:7b:54:0b:c8:d6:ae:ec:5a:9c:
                    92:1e:3d:64:b3:8c:c6:df:bf:c9:41:70:ec:16:72:
                    d5:26:ec:38:55:39:43:d0:fc:fd:18:5c:40:f1:97:
                    eb:d5:9a:9b:8d:1d:ba:da:25:b9:c6:d8:df:c1:15:
                    02:3a:ab:da:6e:f1:3e:2e:f5:5c:08:9c:3c:d6:83:
                    69:e4:10:9b:19:2a:b6:29:57:e3:e5:3d:9b:9f:f0:
                    02:5d
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Key Usage: critical
                Certificate Sign, CRL Sign
            X509v3 Subject Key Identifier: 
                C4:A7:B1:A4:7B:2C:71:FA:DB:E1:4B:90:75:FF:C4:15:60:85:89:10
    Signature Algorithm: sha1WithRSAEncryption
         a3:1a:2c:9b:17:00:5c:a9:1e:ee:28:66:37:3a:bf:83:c7:3f:
         4b:c3:09:a0:95:20:5d:e3:d9:59:44:d2:3e:0d:3e:bd:8a:4b:
         a0:74:1f:ce:10:82:9c:74:1a:1d:7e:98:1a:dd:cb:13:4b:b3:
         20:44:e4:91:e9:cc:fc:7d:a5:db:6a:e5:fe:e6:fd:e0:4e:dd:
         b7:00:3a:b5:70:49:af:f2:e5:eb:02:f1:d1:02:8b:19:cb:94:
         3a:5e:48:c4:18:1e:58:19:5f:1e:02:5a:f0:0c:f1:b1:ad:a9:
         dc:59:86:8b:6e:e9:91:f5:86:ca:fa:b9:66:33:aa:59:5b:ce:
         e2:a7:16:73:47:cb:2b:cc:99:b0:37:48:cf:e3:56:4b:f5:cf:
         0f:0c:72:32:87:c6:f0:44:bb:53:72:6d:43:f5:26:48:9a:52:
         67:b7:58:ab:fe:67:76:71:78:db:0d:a2:56:14:13:39:24:31:
         85:a2:a8:02:5a:30:47:e1:dd:50:07:bc:02:09:90:00:eb:64:
         63:60:9b:16:bc:88:c9:12:e6:d2:7d:91:8b:f9:3d:32:8d:65:
         b4:e9:7c:b1:57:76:ea:c5:b6:28:39:bf:15:65:1c:c8:f6:77:
         96:6a:0a:8d:77:0b:d8:91:0b:04:8e:07:db:29:b6:0a:ee:9d:
         82:35:35:10
-----BEGIN CERTIFICATE-----
MIIDSjCCAjKgAwIBAgIQRK+wgNajJ7qJMDmGLvhAazANBgkqhkiG9w0BAQUFADA/
MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
DkRTVCBSb290IENBIFgzMB4XDTAwMDkzMDIxMTIxOVoXDTIxMDkzMDE0MDExNVow
PzEkMCIGA1UEChMbRGlnaXRhbCBTaWduYXR1cmUgVHJ1c3QgQ28uMRcwFQYDVQQD
Ew5EU1QgUm9vdCBDQSBYMzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
AN+v6ZdQCINXtMxiZfaQguzH0yxrMMpb7NnDfcdAwRgUi+DoM3ZJKuM/IUmTrE4O
rz5Iy2Xu/NMhD2XSKtkyj4zl93ewEnu1lcCJo6m67XMuegwGMoOifooUMM0RoOEq
OLl5CjH9UL2AZd+3UWODyOKIYepLYYHsUmu5ouJLGiifSKOeDNoJjj4XLh7dIN9b
xiqKqy69cK3FCxolkHRyxXtqqzTWMIn/5WgTe1QLyNau7Fqckh49ZLOMxt+/yUFw
7BZy1SbsOFU5Q9D8/RhcQPGX69Wam40dutolucbY38EVAjqr2m7xPi71XAicPNaD
aeQQmxkqtilX4+U9m5/wAl0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNV
HQ8BAf8EBAMCAQYwHQYDVR0OBBYEFMSnsaR7LHH62+FLkHX/xBVghYkQMA0GCSqG
SIb3DQEBBQUAA4IBAQCjGiybFwBcqR7uKGY3Or+Dxz9LwwmglSBd49lZRNI+DT69
ikugdB/OEIKcdBodfpga3csTS7MgROSR6cz8faXbauX+5v3gTt23ADq1cEmv8uXr
AvHRAosZy5Q6XkjEGB5YGV8eAlrwDPGxrancWYaLbumR9YbK+rlmM6pZW87ipxZz
R8srzJmwN0jP41ZL9c8PDHIyh8bwRLtTcm1D9SZImlJnt1ir/md2cXjbDaJWFBM5
JDGFoqgCWjBH4d1QB7wCCZAA62RjYJsWvIjJEubSfZGL+T0yjWW06XyxV3bqxbYo
Ob8VZRzI9neWagqNdwvYkQsEjgfbKbYK7p2CNTUQ
-----END CERTIFICATE-----
```
## Chef Workstation Version

` chef-workstation 21.10.635-1`

## Platform Version

Debian 10 x86_64

## Stack trace
```sh
Generated at 2021-10-03 00:36:44 +0200
OpenSSL::SSL::SSLError: apt_repository[postgresql-binary] (jbox-postgresql::default line 15) had an error: OpenSSL::SSL::SSLError: remote_file[/root/concerto/chef/tmp/cache/https___www_postgresql_org_media_keys_ACCC4CF8_asc] (/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource/apt_repository.rb line 261) had an error: OpenSSL::SSL::SSLError: SSL Error connecting to https://www.postgresql.org/media/keys/ACCC4CF8.asc - SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/http.rb:465:in `rescue in retrying_http_errors'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/http.rb:422:in `retrying_http_errors'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/http.rb:379:in `send_http_request'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/http.rb:228:in `streaming_request'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/provider/remote_file/http.rb:72:in `fetch'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/provider/remote_file/content.rb:74:in `grab_file_from_uri'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/provider/remote_file/content.rb:59:in `try_multiple_sources'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/provider/remote_file/content.rb:44:in `file_for_provider'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/file_content_management/content_base.rb:42:in `tempfile'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/provider/file.rb:457:in `tempfile'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/provider/file.rb:331:in `do_generate_content'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/provider/file.rb:143:in `block in <class:File>'
(eval):2:in `block in action_create'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/provider.rb:301:in `instance_eval'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/provider.rb:301:in `compile_and_converge_action'
(eval):2:in `action_create'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/provider.rb:242:in `run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource.rb:600:in `block in run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource.rb:627:in `with_umask'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource.rb:599:in `run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/runner.rb:74:in `run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/runner.rb:108:in `each'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource_collection.rb:64:in `insert'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/dsl/declare_resource.rb:267:in `declare_resource'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource/apt_repository.rb:261:in `install_key_from_uri'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource/apt_repository.rb:434:in `block (2 levels) in <class:AptRepository>'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource/apt_repository.rb:430:in `each'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource/apt_repository.rb:430:in `block in <class:AptRepository>'
(eval):2:in `block in action_add'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/provider.rb:301:in `instance_eval'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/provider.rb:301:in `compile_and_converge_action'
(eval):2:in `action_add'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/provider.rb:242:in `run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource.rb:600:in `block in run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource.rb:627:in `with_umask'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource.rb:599:in `run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/runner.rb:74:in `run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/runner.rb:108:in `each'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/runner.rb:132:in `block in converge'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource_collection/stepable_iterator.rb:54:in `each_with_index'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/chef-workstation/embedded/lib/ruby/3.0.0/forwardable.rb:238:in `execute_each_resource'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/runner.rb:130:in `converge'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/client.rb:686:in `block in converge'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/client.rb:681:in `catch'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/client.rb:681:in `converge'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/client.rb:705:in `converge_and_save'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/client.rb:285:in `run'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/application.rb:281:in `block in run_chef_client'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/application.rb:264:in `run_chef_client'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/application/base.rb:352:in `run_application'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/application.rb:67:in `run'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/application/solo.rb:60:in `run'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-bin-17.5.22/bin/chef-solo:24:in `<top (required)>'
/usr/bin/chef-solo:376:in `load'
/usr/bin/chef-solo:376:in `<main>'

>>>> Caused by OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)
/opt/chef-workstation/embedded/lib/ruby/3.0.0/net/protocol.rb:46:in `connect_nonblock'
/opt/chef-workstation/embedded/lib/ruby/3.0.0/net/protocol.rb:46:in `ssl_socket_connect'
/opt/chef-workstation/embedded/lib/ruby/3.0.0/net/http.rb:1038:in `connect'
/opt/chef-workstation/embedded/lib/ruby/3.0.0/net/http.rb:970:in `do_start'
/opt/chef-workstation/embedded/lib/ruby/3.0.0/net/http.rb:959:in `start'
/opt/chef-workstation/embedded/lib/ruby/3.0.0/net/http.rb:1512:in `request'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/http/basic_client.rb:73:in `request'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/http.rb:384:in `block in send_http_request'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/http.rb:425:in `block in retrying_http_errors'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/http.rb:423:in `loop'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/http.rb:423:in `retrying_http_errors'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/http.rb:379:in `send_http_request'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/http.rb:228:in `streaming_request'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/provider/remote_file/http.rb:72:in `fetch'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/provider/remote_file/content.rb:74:in `grab_file_from_uri'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/provider/remote_file/content.rb:59:in `try_multiple_sources'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/provider/remote_file/content.rb:44:in `file_for_provider'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/file_content_management/content_base.rb:42:in `tempfile'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/provider/file.rb:457:in `tempfile'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/provider/file.rb:331:in `do_generate_content'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/provider/file.rb:143:in `block in <class:File>'
(eval):2:in `block in action_create'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/provider.rb:301:in `instance_eval'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/provider.rb:301:in `compile_and_converge_action'
(eval):2:in `action_create'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/provider.rb:242:in `run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource.rb:600:in `block in run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource.rb:627:in `with_umask'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource.rb:599:in `run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/runner.rb:74:in `run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/runner.rb:108:in `each'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource_collection.rb:64:in `insert'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/dsl/declare_resource.rb:267:in `declare_resource'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource/apt_repository.rb:261:in `install_key_from_uri'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource/apt_repository.rb:434:in `block (2 levels) in <class:AptRepository>'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource/apt_repository.rb:430:in `each'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource/apt_repository.rb:430:in `block in <class:AptRepository>'
(eval):2:in `block in action_add'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/provider.rb:301:in `instance_eval'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/provider.rb:301:in `compile_and_converge_action'
(eval):2:in `action_add'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/provider.rb:242:in `run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource.rb:600:in `block in run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource.rb:627:in `with_umask'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource.rb:599:in `run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/runner.rb:74:in `run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/runner.rb:108:in `each'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/runner.rb:132:in `block in converge'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource_collection/stepable_iterator.rb:54:in `each_with_index'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/chef-workstation/embedded/lib/ruby/3.0.0/forwardable.rb:238:in `execute_each_resource'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/runner.rb:130:in `converge'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/client.rb:686:in `block in converge'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/client.rb:681:in `catch'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/client.rb:681:in `converge'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/client.rb:705:in `converge_and_save'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/client.rb:285:in `run'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/application.rb:281:in `block in run_chef_client'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/application.rb:264:in `run_chef_client'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/application/base.rb:352:in `run_application'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/application.rb:67:in `run'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.5.22/lib/chef/application/solo.rb:60:in `run'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-bin-17.5.22/bin/chef-solo:24:in `<top (required)>'
/usr/bin/chef-solo:376:in `load'
/usr/bin/chef-solo:376:in `<main>'
```

**Comment by tmsteen** [comment]
I have added the new Let's Encrypt root cert to `/opt/chef-workstation/embedded/ssl/cert.pem` but validation still fails. 

`wget https://letsencrypt.org/certs/isrgrootx1.pem -O /opt/chef-workstation/embedded/ssl/cert.pem` but I still get similar errors.

**Comment by n-rodriguez** [comment]
I've tested workaround 1 (https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/) and it works :

> Workaround 1 (on clients with OpenSSL 1.0.2)
>
> Just remove the expired root certificate (DST Root CA X3) from the trust store used by the OpenSSL 1.0.2 TLS client to verify the identity of TLS servers. If the new ISRG Root X1 self-signed certificate isn’t already in the trust store, add it.

**Comment by tas50** [comment]
The latest release of Workstation resolves this.

**Comment by tmsteen** [comment]
Thanks @tas50, do you know if/when the Docker Hub container will be updated?

Also, @n-rodriguez  can confirm that worked for me as well

**Comment by tmsteen** [comment]
Just rounding out the conversation. The issue I had was that I was pulling the `latest` tag on he Docker Hub image but that is NOT the latest release. Using either the `current` tag or a specific version tag did the trick and got me the latest release.
