### ISSUE TITLE
Workstation 23.2.1028 - /bin/kitchen: warning: Exception in finalizer

### ISSUE THREAD

**Issue by jsloan117** [chef/chef-workstation#3073]
## Description

This appears only in `kitchen verify` stage (haven't seen it in compliance phase) and on Windows.

```ruby
/bin/kitchen: warning: Exception in finalizer #<Proc:0x00007f6578e58e38 /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:33>
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/logging-2.3.1/lib/logging/diagnostic_context.rb:471:in `new': can't alloc thread (ThreadError)
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/logging-2.3.1/lib/logging/diagnostic_context.rb:471:in `create_with_logging_context'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/logging-2.3.1/lib/logging/diagnostic_context.rb:436:in `new'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/timeout-0.3.1/lib/timeout.rb:101:in `create_timeout_thread'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/timeout-0.3.1/lib/timeout.rb:134:in `block in ensure_timeout_thread_created'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/timeout-0.3.1/lib/timeout.rb:132:in `synchronize'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/timeout-0.3.1/lib/timeout.rb:132:in `ensure_timeout_thread_created'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/timeout-0.3.1/lib/timeout.rb:181:in `timeout'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:515:in `query'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/httpclient-2.8.3/lib/httpclient.rb:856:in `request'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/httpclient-2.8.3/lib/httpclient.rb:765:in `post'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/winrm-2.3.6/lib/winrm/http/transport.rb:176:in `send_request'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:42:in `close_shell'
	from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:33:in `block in finalize'
```

## Chef Workstation Version
Chef Workstation version: 23.2.1028
Cookstyle version: 7.32.1
Chef Infra Client version: 18.0.185
Chef InSpec version: 5.18.14
Chef CLI version: 5.6.8
Chef Habitat version: 1.6.521
Test Kitchen version: 3.5.0

## Platform Version
* RHEL7
* Windows 10

**Comment by brentm5** [comment]
Currently getting the same after installing latest on a new host.  Here is my Chef workstation version output


## Chef Workstation Version

Chef Workstation version: 23.3.1030
Chef Infra Client version: 18.0.185
Chef InSpec version: 5.18.14
Chef CLI version: 5.6.8
Chef Habitat version: 1.6.652
Test Kitchen version: 3.5.0
Cookstyle version: 7.32.1

**Comment by jsloan117** [comment]
The latest build still as the issue.

Chef Workstation version: 23.4.1032
Chef InSpec version: 5.21.29
Chef CLI version: 5.6.8
Chef Habitat version: 1.6.652
Test Kitchen version: 3.5.0
Cookstyle version: 7.32.2
Chef Infra Client version: 18.2.7

**Comment by jakauppila** [comment]
Looks like this would be addressed in https://github.com/WinRb/WinRM/pull/339

**Comment by clintoncwolfe** [comment]
Just an update, we believe a Ruby 3.3 update that we are in the middle of may help resolve this issue. Stay tuned.

**Comment by sandratiffin** [comment]
I'm seeing this issue in:

Chef Workstation version: 24.6.1066
Chef Infra Client version: 18.4.12
Chef InSpec version: 5.22.50
Chef CLI version: 5.6.14
Chef Habitat version: 1.6.1041
Test Kitchen version: 3.6.0
Cookstyle version: 7.32.8
