### ISSUE TITLE
knife commands fail with SSL error when using FIPS kernel

### ISSUE THREAD

**Issue by msgarbossa** [chef/chef-workstation#316]
## Description
When using FIPS kernel, the knife and chef-client commands fail with the following error:
```
ERROR: OpenSSL::OpenSSLError: This version of OpenSSL does not support FIPS mode
```
The issue only occurs in Chef Workstation and not in ChefDK 3.4.38.

## Chef Workstation Version
0.2.29-1 (stable) and 0.2.32-1 (current)

## Platform Version
RHEL 7.6

## Details

knife:
```
# /opt/chef-workstation/bin/knife node list
ERROR: OpenSSL::OpenSSLError: This version of OpenSSL does not support FIPS mode
```

chef-client:
```
# /opt/chef-workstation/bin/chef-client
Traceback (most recent call last):
        9: from /opt/chef-workstation/bin/chef-client:296:in `<main>'
        8: from /opt/chef-workstation/bin/chef-client:296:in `load'
        7: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47/bin/chef-client:25:in `<top (required)>'
        6: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47/lib/chef/application.rb:64:in `run'
        5: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47/lib/chef/application/client.rb:313:in `reconfigure'
        4: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47/lib/chef/application.rb:55:in `reconfigure'
        3: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47/lib/chef/application.rb:99:in `configure_chef'
        2: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-config-14.6.47/lib/chef-config/config.rb:587:in `init_openssl'
        1: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-config-14.6.47/lib/chef-config/config.rb:1132:in `enable_fips_mode'
/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-config-14.6.47/lib/chef-config/config.rb:1132:in `fips_mode=': This version of OpenSSL does not support FIPS mode (OpenSSL::OpenSSLError)
```

## Workaround
As documented in [chef/chef issue 5533](https://github.com/chef/chef/issues/5533#issuecomment-260859211), the following command resolves the issue for the current shell.
```
export CHEF_FIPS=""
```

The ChefDK packages do not have this issue and do not require the workaround, including the latest stable ChefDK 3.4.38 package.

**Comment by robbkidd** [comment]
@msgarbossa Curses! Yes. Chef Workstation has not yet received the FIPS build settings used for ChefDK. We'll get on that!

**Comment by tyler-ball** [comment]
Note: Slack conversation says that only OpenSSL 1.0.2 supports FIPS

**Comment by tyler-ball** [comment]
It looks like `CHEF_FIPS=""` disables fips - https://github.com/chef/chef/blob/985c26111718397071ad42b22a77345238c6a510/chef-config/lib/chef-config/config.rb#L668
