### ISSUE TITLE
Chef Workstation 0.7.4 on MacOS 10.14.5 fails when running chef-run with uninitialized constant Psych::Syck::PrivateType NameError

### ISSUE THREAD

**Issue by predatorian3** [chef/chef-workstation#418]
## Description

Fresh install of Chef Workstation 0.7.4 on MacOS 10.14.5 using zsh. When running chef-run, I get the following Errors.

```bash
➜  ~ chef -v
Chef Workstation version: 0.7.4
Chef Infra Client version: 15.1.36
Chef InSpec version: 4.7.3
Test Kitchen version: 2.2.5
Foodcritic version: 16.1.1
Cookstyle version: 5.0.0
➜  ~ chef-run --help
Traceback (most recent call last):
	18: from /usr/local/bin/chef-run:343:in `<main>'
	17: from /usr/local/bin/chef-run:343:in `load'
	16: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.3.0/bin/chef-run:19:in `<top (required)>'
	15: from /opt/chef-workstation/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	14: from /opt/chef-workstation/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	13: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.3.0/lib/chef_apply/startup.rb:18:in `<top (required)>'
	12: from /opt/chef-workstation/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /opt/chef-workstation/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	10: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.3.0/lib/chef_apply/text.rb:18:in `<top (required)>'
	 9: from /opt/chef-workstation/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /opt/chef-workstation/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 7: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/r18n-desktop-3.2.0/lib/r18n-desktop.rb:20:in `<top (required)>'
	 6: from /opt/chef-workstation/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /opt/chef-workstation/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 4: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/r18n-core-3.2.0/lib/r18n-core.rb:38:in `<top (required)>'
	 3: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/r18n-core-3.2.0/lib/r18n-core.rb:157:in `<module:R18n>'
	 2: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/r18n-core-3.2.0/lib/r18n-core.rb:157:in `new'
	 1: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/r18n-core-3.2.0/lib/r18n-core/yaml_loader.rb:43:in `initialize'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/r18n-core-3.2.0/lib/r18n-core/yaml_methods.rb:28:in `detect_yaml_private_type': uninitialized constant Psych::Syck::PrivateType (NameError)
➜  ~ chef-run -v
Traceback (most recent call last):
	18: from /usr/local/bin/chef-run:343:in `<main>'
	17: from /usr/local/bin/chef-run:343:in `load'
	16: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.3.0/bin/chef-run:19:in `<top (required)>'
	15: from /opt/chef-workstation/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	14: from /opt/chef-workstation/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	13: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.3.0/lib/chef_apply/startup.rb:18:in `<top (required)>'
	12: from /opt/chef-workstation/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /opt/chef-workstation/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	10: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.3.0/lib/chef_apply/text.rb:18:in `<top (required)>'
	 9: from /opt/chef-workstation/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /opt/chef-workstation/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 7: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/r18n-desktop-3.2.0/lib/r18n-desktop.rb:20:in `<top (required)>'
	 6: from /opt/chef-workstation/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /opt/chef-workstation/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 4: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/r18n-core-3.2.0/lib/r18n-core.rb:38:in `<top (required)>'
	 3: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/r18n-core-3.2.0/lib/r18n-core.rb:157:in `<module:R18n>'
	 2: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/r18n-core-3.2.0/lib/r18n-core.rb:157:in `new'
	 1: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/r18n-core-3.2.0/lib/r18n-core/yaml_loader.rb:43:in `initialize'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/r18n-core-3.2.0/lib/r18n-core/yaml_methods.rb:28:in `detect_yaml_private_type': uninitialized constant Psych::Syck::PrivateType (NameError)
➜  ~ chef exec chef-run --help
+---------------------------------------------+
            Chef License Acceptance

Before you can continue, 3 product licenses
must be accepted. View the license at
https://www.chef.io/end-user-license-agreement/

Licenses that need accepting:
  * Chef Workstation
  * Chef Infra Client
  * Chef InSpec

Do you accept the 3 product licenses (yes/no)?

> yes

Persisting 3 product licenses...
✔ 3 product licenses persisted.

+---------------------------------------------+
Traceback (most recent call last):
	18: from /opt/chef-workstation/bin/chef-run:343:in `<main>'
	17: from /opt/chef-workstation/bin/chef-run:343:in `load'
	16: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.3.0/bin/chef-run:19:in `<top (required)>'
	15: from /opt/chef-workstation/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	14: from /opt/chef-workstation/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	13: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.3.0/lib/chef_apply/startup.rb:18:in `<top (required)>'
	12: from /opt/chef-workstation/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /opt/chef-workstation/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	10: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.3.0/lib/chef_apply/text.rb:18:in `<top (required)>'
	 9: from /opt/chef-workstation/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /opt/chef-workstation/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 7: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/r18n-desktop-3.2.0/lib/r18n-desktop.rb:20:in `<top (required)>'
	 6: from /opt/chef-workstation/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /opt/chef-workstation/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 4: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/r18n-core-3.2.0/lib/r18n-core.rb:38:in `<top (required)>'
	 3: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/r18n-core-3.2.0/lib/r18n-core.rb:157:in `<module:R18n>'
	 2: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/r18n-core-3.2.0/lib/r18n-core.rb:157:in `new'
	 1: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/r18n-core-3.2.0/lib/r18n-core/yaml_loader.rb:43:in `initialize'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/r18n-core-3.2.0/lib/r18n-core/yaml_methods.rb:28:in `detect_yaml_private_type': uninitialized constant Psych::Syck::PrivateType (NameError)
```

## Chef Workstation Version

```bash
➜  ~ chef -v
Chef Workstation version: 0.7.4
Chef Infra Client version: 15.1.36
Chef InSpec version: 4.7.3
Test Kitchen version: 2.2.5
Foodcritic version: 16.1.1
Cookstyle version: 5.0.0
```

## Platform Version

```bash
➜  ~ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132
```

**Comment by afiune** [comment]
Hello @predatorian3 - I'm sorry that you are facing this problem, I have tried to replicate the issue but I was unable to do so, I just installed the latest version of Chef Workstation and it seems to be working:
```
➜  ~ ll /usr/local/bin/chef-run
lrwxr-xr-x  1 root  admin    34B Jul 30 01:31 /usr/local/bin/chef-run -> /opt/chef-workstation/bin/chef-run
➜  ~ ll /opt/chef-workstation/bin/chef-run
-rwxr-xr-x  1 root  wheel    11K Jul 16 01:19 /opt/chef-workstation/bin/chef-run
➜  ~ chef-run -v
chef-run: 0.3.0
➜  ~ chef -v
Chef Workstation version: 0.7.4
Chef Infra Client version: 15.1.36
Chef InSpec version: 4.7.3
Test Kitchen version: 2.2.5
Foodcritic version: 16.1.1
Cookstyle version: 5.0.0
➜  ~ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132
```

I am wondering if this was an upgrade instead of a fresh install (I did a fresh one), if it is an upgrade, do you happen to know which version you upgraded from? also, could you try to remove it and try to install latest and see if that behaves in the same manner?

**Comment by tyler-ball** [comment]
I think this is fixed in the latest version of Chef Workstation (fixed some gems Test Kitchen pulls in) and we have not heard back from the reporter. Going to close this. @predatorian3 Please re-open if you still find an issue in the latest version of Chef Workstation!
