### ISSUE TITLE
chef-run fails to connect to a host

### ISSUE THREAD

**Issue by mik047** [chef/chef-workstation#483]
## Description

**chef-run** fails to connect to a host; complaining about following.

> CHEFINT001
An unexpected error has occurred:
  backtrace must be Array of String

The problem happens while connecting using **ssh**.

I have only found something relevant [here](https://github.com/inspec/train/issues/506) - However it seems it requires some special configuration in **sudoers** file and I am not intending to go for it.

I have tried connecting using ssh (with the same key, user combination) and it is simply able to connect to the host.

I have also noticed that, when I try to connect to the box as _root_, it works fine. Its only when I try to login as a specific user, it complains.

Is there any permanent fix to this? Or some workarounds?

Here is the stack strace

> Backtrace:
TypeError: backtrace must be Array of String
	/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.1.19/lib/train/extras/command_wrapper.rb:173:in `set_backtrace'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.1.19/lib/train/extras/command_wrapper.rb:173:in `raise'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.1.19/lib/train/extras/command_wrapper.rb:173:in `load'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.1.19/lib/train/transports/ssh_connection.rb:53:in `initialize'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.1.19/lib/train/transports/ssh.rb:238:in `new'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.1.19/lib/train/transports/ssh.rb:238:in `create_new_connection'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.1.19/lib/train/transports/ssh.rb:82:in `connection'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.3.3/lib/chef_apply/target_host.rb:117:in `connect!'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.3.3/lib/chef_apply/cli.rb:333:in `do_connect'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.3.3/lib/chef_apply/cli.rb:181:in `connect_target'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.3.3/lib/chef_apply/cli.rb:166:in `block (2 levels) in render_converge'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.3.3/lib/chef_apply/ui/terminal/job.rb:31:in `run'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.3.3/lib/chef_apply/ui/terminal.rb:60:in `block (2 levels) in render_parallel_jobs'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/tty-spinner-0.9.1/lib/tty/spinner.rb:225:in `execute_job'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/tty-spinner-0.9.1/lib/tty/spinner/multi.rb:150:in `block (2 levels) in auto_spin'

And here is the relevant default log (in debug mode)

> DEBUG: [ChefApply::Action::GenerateCookbookFromRecipe] Action: generating, Action Data: []
DEBUG: Beginning to look for recipe specified as try::try
DEBUG: [ChefApply::Action::GenerateCookbookFromRecipe] Action: success, Action Data: []
DEBUG: [ChefApply::Action::GenerateLocalPolicy] Action: generating, Action Data: []
DEBUG: [ChefApply::Action::GenerateLocalPolicy] Action: exporting, Action Data: []
DEBUG: [ChefApply::Action::GenerateLocalPolicy] Action: success, Action Data: []
DEBUG: [SSH] Using Agent keys as no password or key file have been specified
DEBUG: [SSH] uzer@dummybox<{:user_known_hosts_file=>"/dev/null", :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :auth_methods=>["none", "publickey"], :keys_only=>nil, :keys=>nil, :password=>"<hidden>", :forward_agent=>nil, :non_interactive=>true, :verify_host_key=>:never}> (cmd.exe /c ver)
DEBUG: [SSH] opening connection to uzer@dummybox<{:user_known_hosts_file=>"/dev/null", :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :auth_methods=>["none", "publickey"], :keys_only=>nil, :keys=>nil, :password=>"<hidden>", :forward_agent=>nil, :non_interactive=>true, :verify_host_key=>:never}>
DEBUG: [SSH] uzer@dummybox<{:user_known_hosts_file=>"/dev/null", :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :auth_methods=>["none", "publickey"], :keys_only=>nil, :keys=>nil, :password=>"<hidden>", :forward_agent=>nil, :non_interactive=>true, :verify_host_key=>:never}> (uname -s)
DEBUG: [SSH] uzer@dummybox<{:user_known_hosts_file=>"/dev/null", :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :auth_methods=>["none", "publickey"], :keys_only=>nil, :keys=>nil, :password=>"<hidden>", :forward_agent=>nil, :non_interactive=>true, :verify_host_key=>:never}> (uname -m)
DEBUG: [SSH] uzer@dummybox<{:user_known_hosts_file=>"/dev/null", :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :auth_methods=>["none", "publickey"], :keys_only=>nil, :keys=>nil, :password=>"<hidden>", :forward_agent=>nil, :non_interactive=>true, :verify_host_key=>:never}> (test -f /etc/debian_version && cat /etc/debian_version)
DEBUG: [SSH] uzer@dummybox<{:user_known_hosts_file=>"/dev/null", :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :auth_methods=>["none", "publickey"], :keys_only=>nil, :keys=>nil, :password=>"<hidden>", :forward_agent=>nil, :non_interactive=>true, :verify_host_key=>:never}> (test -f /etc/lsb-release && cat /etc/lsb-release)
DEBUG: [SSH] uzer@dummybox<{:user_known_hosts_file=>"/dev/null", :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :auth_methods=>["none", "publickey"], :keys_only=>nil, :keys=>nil, :password=>"<hidden>", :forward_agent=>nil, :non_interactive=>true, :verify_host_key=>:never}> (sudo echo)

## Chef Workstation Version

> Chef Workstation version: 1.0.11
Chef Infra Client version: 15.2.20
Chef InSpec version: 4.10.4
Test Kitchen version: 2.2.5
Foodcritic version: 16.1.1
Cookstyle version: 0.72.0

## Platform Version

> os details = Ubuntu 18.04 LTS (64 bit version)
shell = bash

**Comment by mik047** [comment]
Hi @afiune, thanks for the update. 

Well, I have already referred to the provided link and the respective docs. I am trying to run a cookbook actually using _chef-run_. 

**Problem is:**

chef-run is not able to ssh into the target even though the exact same configurations (of ssh-conf, username, etc.) are working fine if I use plane ssh command line.

Additionally, this is only happening if I use _root_ user for connecting to the target node. (note that the target node is Ubuntu 18.04 LTS).

The stack trace shows chef failing when it attempts -> **(sudo echo)** during ssh. That is why my initial looking around lead me [here](https://github.com/inspec/train/issues/506). It is the exact same error I am getting and with similar stack trace as well. (Not sure if that is _actually_ the problem is!)

All I am asking is, 
> If the solution requires some additional steps for Ubuntu (especially 18.04) users, then kindly highlight it in the docs. 
> If the problem is somewhere else, then kindly enlighten me! (As I have checked every other angle and find myself already following all the steps that are laid out at [chef docs](https://www.chef.sh/docs/chef-workstation/chef-run-users-guide/).

Happy to give specific configurations (ssh conf, further os details, etc.) if the need be.

**Comment by mik047** [comment]
Found the mistake I was doing...

Basically I was required to also provide `--sudo-password <password>` for the _non-root_ user. 

Thanks for your time, so far!
