### ISSUE TITLE
no_proxy doesn't work as advertised when using chef exec rspec

### ISSUE THREAD

**Issue by jblaine** [chef/chef-workstation#655]
# Description

`chef exec rspec` is not able to function due to it trying to make connections to 127.0.0.1 through our HTTP proxy, because it shouldn't be doing that. It appears `no_proxy` in `knife.rb` is being ignored or the documentation for it does not accurately reflect the proper syntax for the setting.
# ChefDK Version

Chef Development Kit Version: 0.14.25
chef-client version: 12.10.24
berks version: 4.3.3
kitchen version: 1.8.0
# Platform Version

RHEL 7
# Replication Case
1. Configure `knife.rb`

```
    http_proxy               'http://proxy.our.org:80'
    https_proxy              'http://proxy.our.org:80'
    no_proxy                 '*.our.org, localhost, 127.0.0.1'
```
1. Run `chef generate cookbook no_proxy_test` with the default cookbook generator
2. `cd no_proxy_test`
3. Run `chef exec rspec` and you'll see it trying to talk through a proxy (and failing) to, I assume... chef-zero. This can be seen more clearly with (on Linux): `strace -qq -f -e trace=connect chef exec rspec`. The stacktrace in **Stacktrace** below shows the failure.
4. Comment out the `http_proxy` and `https_proxy` lines in `knife.rb` (thereby defining no proxies to use, like `no_proxy` should be doing...) and you will succeed as shown in the code output below.

```
    .

    Finished in 2.9 seconds (files took 2.84 seconds to load)
    1 example, 0 failures
```
# Stacktrace

```
F

Failures:

  1) no_proxy_test::default When all attributes are default, on an unspecified platform converges successfully
     Failure/Error: expect { chef_run }.to_not raise_error

       expected no Exception, got #<Net::HTTPFatalError: 504 "Gateway Timeout"> with backtrace:
         # ./spec/unit/recipes/default_spec.rb:13:in `block (3 levels) in <top (required)>'
         # ./spec/unit/recipes/default_spec.rb:17:in `block (4 levels) in <top (required)>'
         # ./spec/unit/recipes/default_spec.rb:17:in `block (3 levels) in <top (required)>'
     # ./spec/unit/recipes/default_spec.rb:17:in `block (3 levels) in <top (required)>'

Finished in 0.5396 seconds (files took 3.1 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/unit/recipes/default_spec.rb:16 # no_proxy_test::default When all attributes are default, on an unspecified platform converges successfully
```

**Comment by tyler-ball** [comment]
This definitely seems like we need to handle the situation where there are existing proxy settings in the environment and in the `~/.chef/config.rb` file. I _think_ overwriting the existing proxy environment variables when a Chef tool is run seems like the right thing, but that is also a form of transparent magic that generally isn't easy to troubleshoot. So maybe merging them? We need to investigate this
