### ISSUE TITLE
chef-run on windows 10 ignore build-in ssh config for key

### ISSUE THREAD

**Issue by herz0g** [chef/chef-workstation#741]
## Description

Hi, when I start chef-run I got error messages that my ssh config file isn't setup correctly. I have a ssh config file in my home folder which one is working if I use build-in ssh - it will connect to the definied server and ask for the definied key within my config file:

```
PS C:\Users\chg> ssh mailsrv
Enter passphrase for key '.\.ssh\id_rsa':
...
```

But it is not working if I use chef-run:

```
PS C:\Users\chg\Documents\chef-repo\cookbooks\debian10_sec\recipes> chef-run mailsrv default.rb
 [✔] Packaging cookbook... done!
 [✔] Generating local policyfile... exporting... done!
[✖] Applying debian10_sec::default from C:/Users/chg/Documents/chef-repo/cookbooks/debian10_sec to target.              |__ [✖] [mailsrv] No authentication methods available.                                                                  
No authentication methods available.
Try...
- Provide a password with "--password PASSWORD"
- Provide a key with "-identity-file PATH/TO/FILE"
- Enable ssh-agent and add keys
- Add a host entry to your ssh configuration

Additional instructions can be found in the troubleshooting documentation:
https://www.chef.sh/docs/chef-workstation/troubleshooting/#error-code-cheftrn007
```

Where do chef-run search for the config file?

## Chef Workstation Version
Chef Workstation version: 0.11.21
Chef Infra Client version: 15.4.45
Chef InSpec version: 4.18.0
Chef CLI version: 2.0.0
Test Kitchen version: 2.3.4
Cookstyle version: 5.10.13
chef-run: 0.4.6

## Platform Version
Windows 10 Pro

stack-trace:
```
--------------------------------------------------------------------------------
2019-11-25 16:24:24 +0100: Error encountered while running the following:
  mailsrv default.rb
Backtrace:
ChefApply::TargetHost::ConnectionFailure: ChefApply::TargetHost::ConnectionFailure
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.4.6/lib/chef_apply/target_host.rb:131:in `rescue in connect!'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.4.6/lib/chef_apply/target_host.rb:114:in `connect!'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.4.6/lib/chef_apply/cli.rb:334:in `do_connect'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.4.6/lib/chef_apply/cli.rb:180:in `connect_target'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.4.6/lib/chef_apply/cli.rb:165:in `block (2 levels) in render_converge'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.4.6/lib/chef_apply/ui/terminal/job.rb:31:in `run'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.4.6/lib/chef_apply/ui/terminal.rb:60:in `block (2 levels) in render_parallel_jobs'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/tty-spinner-0.9.1/lib/tty/spinner.rb:225:in `execute_job'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/tty-spinner-0.9.1/lib/tty/spinner/multi.rb:150:in `block (2 levels) in auto_spin'
Caused by: Train::ClientError: Your SSH Agent has no keys added, and you have not specified a password or a key file
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/transports/ssh.rb:106:in `validate_options'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/transports/ssh.rb:76:in `connection'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.4.6/lib/chef_apply/target_host.rb:118:in `connect!'
	... 7 more
```

**Comment by herz0g** [comment]
Also:

added my key with ssh-add after enabling ssh-agent
-> not working

added the key file with argument -i for chef-run
-> error:
```
2019-11-25 21:56:20 +0100: Error encountered while running the following:
  mailsrv -i C:\Users\chg\.ssh\id_rsa default.rb
Backtrace:
ChefApply::TargetHost::ConnectionFailure: ChefApply::TargetHost::ConnectionFailure
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.4.6/lib/chef_apply/target_host.rb:131:in `rescue in connect!'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.4.6/lib/chef_apply/target_host.rb:114:in `connect!'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.4.6/lib/chef_apply/cli.rb:334:in `do_connect'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.4.6/lib/chef_apply/cli.rb:180:in `connect_target'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.4.6/lib/chef_apply/cli.rb:165:in `block (2 levels) in render_converge'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.4.6/lib/chef_apply/ui/terminal/job.rb:31:in `run'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.4.6/lib/chef_apply/ui/terminal.rb:60:in `block (2 levels) in render_parallel_jobs'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/tty-spinner-0.9.1/lib/tty/spinner.rb:225:in `execute_job'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/tty-spinner-0.9.1/lib/tty/spinner/multi.rb:150:in `block (2 levels) in auto_spin'
Caused by: Train::Transports::SSHFailed: SSH command failed (the given identity is known, but the private key could not be loaded: OpenSSL::PKey::PKeyError (Could not parse PKey: no start line))
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/transports/ssh_connection.rb:231:in `rescue in run_command_via_connection'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/transports/ssh_connection.rb:219:in `run_command_via_connection'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/plugins/base_connection.rb:128:in `run_command'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/platforms/detect/helpers/os_windows.rb:9:in `check_cmd'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/platforms/detect/helpers/os_windows.rb:4:in `detect_windows'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/platforms/detect/specifications/os.rb:29:in `block in load'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/platforms/detect/scanner.rb:46:in `instance_eval'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/platforms/detect/scanner.rb:46:in `block in scan_children'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/platforms/detect/scanner.rb:45:in `each'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/platforms/detect/scanner.rb:45:in `scan_children'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/platforms/detect/scanner.rb:33:in `block in scan'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/platforms/detect/scanner.rb:27:in `each'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/platforms/detect/scanner.rb:27:in `scan'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/platforms/detect.rb:9:in `scan'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/plugins/base_connection.rb:116:in `platform'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/extras/command_wrapper.rb:166:in `load'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/transports/ssh_connection.rb:53:in `initialize'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/transports/ssh.rb:240:in `new'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/transports/ssh.rb:240:in `create_new_connection'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/transports/ssh.rb:82:in `connection'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-apply-0.4.6/lib/chef_apply/target_host.rb:118:in `connect!'
	... 7 more
Caused by: Net::SSH::Authentication::KeyManagerError: the given identity is known, but the private key could not be loaded: OpenSSL::PKey::PKeyError (Could not parse PKey: no start line)
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:144:in `rescue in sign'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:141:in `sign'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/methods/publickey.rb:62:in `authenticate_with'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/methods/publickey.rb:20:in `block in authenticate'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:122:in `block in each_identity'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:119:in `each'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:119:in `each_identity'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/session.rb:85:in `block in authenticate'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/session.rb:71:in `each'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/session.rb:71:in `authenticate'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh.rb:250:in `start'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/transports/ssh_connection.rb:185:in `establish_connection'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/transports/ssh_connection.rb:254:in `session'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/transports/ssh_connection.rb:223:in `run_command_via_connection'
	... 26 more
Caused by: OpenSSL::PKey::PKeyError: Could not parse PKey: no start line
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/key_factory.rb:155:in `read'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/key_factory.rb:155:in `read'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/key_factory.rb:61:in `load_data_private_key'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/key_factory.rb:44:in `load_private_key'
	C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:142:in `sign'
	... 39 more
```

**Comment by afiune** [comment]
Hello @herz0g - Thank you for reporting this issue, we have confirmed that this is
a bug and we will investigate what are the complication on Windows systems. We will
keep you posted of any discovery or fixes we do.
