### ISSUE TITLE
Resolve FFI warnings from bundled tooling

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation#904]
FFI 1.12 introduced warnings if you try to override a struct layout, which we are apparently doing. I'm pinning to < 1.12, but we need 1.12 for Ruby 2.7 support. This needs to get fixed in our deps.

It produces output similar to this (this is actually from DK, but it's the same)

```
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/ffi-1.12.1-x64-mingw32/lib/ffi/struct.rb:207:in `layout': [DEPRECATION] Struct layout is already defined for class Windows::ServiceStructs::SERVICE_STATUS_PROCESS. Redefinition as in C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/win32-service-2.1.4/lib/win32/windows/structs.rb:72:in `<class:SERVICE_STATUS_PROCESS>' will be disallowed in ffi-2.0. (StructuredWarnings::StandardWarning)
```

## Chef Workstation Version
latest

## Platform Version
Windows

**Comment by tas50** [comment]
This is fixed with #914
