### ISSUE TITLE
Dependency bumping in the pipeline is borked

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-workstation#986]
## Description
Pipeline is red, lets get this fixed. We also missed some dependency bumps that should have gone out in 0.16.31 so lets get those merged and do another 0.16 release to get these dependencies out.

```
+ bundle exec rake update
bundler: failed to load command: rake (/opt/asdf/installs/ruby/2.6.5/bin/rake)
Bundler::GemNotFound: Could not find i18n-1.8.2 in any of the sources
  /opt/asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/spec_set.rb:91:in `block in materialize'
  /opt/asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/spec_set.rb:85:in `map!'
  /opt/asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/spec_set.rb:85:in `materialize'
  /opt/asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/definition.rb:170:in `specs'
  /opt/asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/definition.rb:237:in `specs_for'
  /opt/asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/definition.rb:226:in `requested_specs'
  /opt/asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:108:in `block in definition_method'
  /opt/asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:20:in `setup'
  /opt/asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler.rb:107:in `setup'
  /opt/asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/setup.rb:20:in `<top (required)>'
  /opt/asdf/installs/ruby/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /opt/asdf/installs/ruby/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

## Chef Workstation Version
0.16.31

**Comment by jonsmorrow** [comment]
https://app.zenhub.com/workspaces/chef-workstation-5c0aced04b5806bc2bfb9347/issues/chef/chef-workstation/982
